### ISSUE TITLE
Feature: handle zero ratio in `analyze allocate --rebalance`

### ISSUE THREAD

**Issue by rapidleft** [sarvjeets/lakshmi#48]
It can be convenient to set an asset class allocation ratio to 0, for example to exit a position of a certain fund or market segment.

It seems like most `lak` commands handle this just fine, however `lak analyze allocate --rebalance` does not allow this.
```
$ lak analyze allocate --account MyBrokerage --rebalance
<...>
AssertionError: Desired ratio of asset class MyZeroAsset cannot be zero.
```
I think this should work. The `MyZeroAsset` asset should be rebalanced to 0 and the funds moved to other assets.

A hacky work around is to set the ratio to to almost zero e.g. `0.00000000000001`.

**Comment by sarvjeets** [comment]
rapidleft: Not sure if you are still working on this, do you mind if I try to fix this issue?
