### ISSUE TITLE
Problem with portfolio with only ManualAsset

### ISSUE THREAD

**Issue by CJKohler** [sarvjeets/lakshmi#77]
I was setting up my portfoilo.yaml file using  "lak add asset -p ManualAsset -t institution". Because of proprietary funds in my retirement portfolio. All my assets where of type "ManualAsset". 

When I ran 
`lak list total`
I get : "AssertionError: prefetch_add must be called before calling prefetch"

Adding in one VanguardFund fixed the problem. I'm guessing the assumption is that every portfolio has some prices that need to be fetched, which was not true in my case

**Comment by sarvjeets** [comment]
Thanks for reporting this bug. I pushed the fix in version 3.0.1
